handle action trace v1
worldwide-asset-exchange/eosio-statereceiver pull request #5
Opened 2022-11-23 14:21 UTC by danielAlvess

2022-11-23 23:40 UTC, porkchop requested changes
Good idea @danielAlvess . One very minor nitpick in there for you. Also, can you bump the version in packge.json and package-lock.json from `2.1.2` to `2.2.0` as well please? I'll merge and publish the changes when these are done

2022-11-23 23:40 UTC, porkchop commented on examples/connection.js
> +// const { deserialize } = require('../src/deserialize');
can we remove this if it is unused please?

2022-11-24 02:03 UTC, danielAlvess commented
Fixed and bump to version 2.2.0

2022-11-24 18:31 UTC, porkchop commented
thanks @danielAlvess LGTM!

2022-11-24 18:31 UTC, merged